### PR TITLE
Order assign

### PR DESCRIPTION
**Pull request by DipeshMainali**
## Breaking changes
Added endpoints to assign orders to fulfillment manager and delivery representative.
Added simple schema to added exceptional notes

### CODE REVIEW

**Comment by nnnnat** [comment]
@DipeshMainali thanks for contributing to the Reaction Commerce project, I always love to see new community members cutting Pull Request! I've done a quick review of this PR and I have a few general comments, this is a pretty large change to our API so I'd like to see a more in depth description around the use case and how these code changes address it. 29 files is also a pretty large PR for our small team to digest, if this feature enhancement could be broken out into multiple smaller PRs that incrementally add the functionality your looking for that would be a lot easier (and safer) for us to review and merge.

**Comment by nnnnat** [comment]
@DipeshMainali & @dineshdb did y'all make a PR to this repo by mistake?

**Comment by dineshdb** [comment]
Hey @nnnnat, @DipeshMainali was supposed to send this PR at our fork. This is by mistake here and can be safely closed.

**Comment by nnnnat** [comment]
LOL @dineshdb not a problem it happens on occasion. Would love to talk with y'all at some point to get an understanding of how you're using the project and collect any feedback you've got for the core team.

**Comment by dineshdb** [comment]
Sure @nnnnat, would love to.

**Pull request closed without merging**
